function render_header(container) { // Vår funktion render_header(container)

  const imagePaths = [
    "media/geo_images/argentina_normal_1.jpg",
    "media/geo_images/argentina_normal_2.jpg",
    "media/geo_images/argentina_normal_3.jpg",
    "media/geo_images/argentina_normal_4.jpg",
    "media/geo_images/atlanta_normal_1.jpg",
    "media/geo_images/atlanta_normal_2.jpg",
    "media/geo_images/australia_normal_1.jpg",
    "media/geo_images/australia_normal_2.jpg",
    "media/geo_images/bath_normal_1.jpg",
    "media/geo_images/bath_normal_2.jpg",
    "media/geo_images/boston_normal_1.jpg",
    "media/geo_images/boston_normal_2.jpg",
    "media/geo_images/buenos_aires_normal_1.jpg",
    "media/geo_images/buenos_aires_normal_2.jpg",
    "media/geo_images/buffalo_normal_1.jpg",
    "media/geo_images/buffalo_normal_2.jpg",
    "media/geo_images/canberra_normal_1.jpg",
    "media/geo_images/canberra_normal_2.jpg",
    "media/geo_images/chile_normal_1.jpg",
    "media/geo_images/chile_normal_2.jpg",
    "media/geo_images/chile_normal_3.jpg",
    "media/geo_images/chile_normal_4.jpg",
    "media/geo_images/cordoba_normal_1.jpg",
    "media/geo_images/cordoba_normal_2.jpg",
    "media/geo_images/edinburgh_normal_1.jpg",
    "media/geo_images/edinburgh_normal_2.jpg",
    "media/geo_images/france_normal_1.jpg",
    "media/geo_images/france_normal_2.jpg",
    "media/geo_images/france_normal_3.jpg",
    "media/geo_images/france_normal_4.jpg",
    "media/geo_images/france_normal_5.jpg",
    "media/geo_images/france_normal_6.jpg",
    "media/geo_images/guadalajara_normal_1.jpg",
    "media/geo_images/guadalajara_normal_2.jpg",
    "media/geo_images/london_normal_1.jpg",
    "media/geo_images/london_normal_2.jpg",
    "media/geo_images/london_normal_3.jpg",
    "media/geo_images/london_normal_4.jpg",
    "media/geo_images/lund_normal_1.jpg",
    "media/geo_images/lund_normal_2.jpg",
    "media/geo_images/lyon_normal_1.jpg",
    "media/geo_images/lyon_normal_2.jpg",
    "media/geo_images/lyon_normal_3.jpg",
    "media/geo_images/lyon_normal_4.jpg",
    "media/geo_images/madrid_normal_1.jpg",
    "media/geo_images/madrid_normal_2.jpg",
    "media/geo_images/madrid_normal_3.jpg",
    "media/geo_images/madrid_normal_4.jpg",
    "media/geo_images/malmo_normal_1.jpg",
    "media/geo_images/malmo_normal_2.jpg",
    "media/geo_images/manchester_normal_1.jpg",
    "media/geo_images/manchester_normal_2.jpg",
    "media/geo_images/manchester_normal_3.jpg",
    "media/geo_images/manchester_normal_4.jpg",
    "media/geo_images/melbourne_normal_1.jpg",
    "media/geo_images/melbourne_normal_2.jpg",
    "media/geo_images/mexico_city_normal_1.jpg",
    "media/geo_images/mexico_city_normal_2.jpg",
    "media/geo_images/mexico_normal_1.jpg",
    "media/geo_images/mexico_normal_2.jpg",
    "media/geo_images/mexico_normal_3.jpg",
    "media/geo_images/mexico_normal_4.jpg",
    "media/geo_images/mexico_normal_5.jpg",
    "media/geo_images/mexico_normal_6.jpg",
    "media/geo_images/new_york_normal_1.jpg",
    "media/geo_images/new_york_normal_2.jpg",
    "media/geo_images/nice_normal_1.jpg",
    "media/geo_images/nice_normal_2.jpg",
    "media/geo_images/oaxaca_normal_1.jpg",
    "media/geo_images/oaxaca_normal_2.jpg",
    "media/geo_images/paris_normal_1.jpg",
    "media/geo_images/paris_normal_2.jpg",
    "media/geo_images/paris_normal_3.jpg",
    "media/geo_images/paris_normal_4.jpg",
    "media/geo_images/salamanca_normal_1.jpg",
    "media/geo_images/salamanca_normal_2.jpg",
    "media/geo_images/salamanca_normal_3.jpg",
    "media/geo_images/salamanca_normal_4.jpg",
    "media/geo_images/san_francisco_normal_1.jpg",
    "media/geo_images/san_francisco_normal_2.jpg",
    "media/geo_images/santiago_normal_1.jpg",
    "media/geo_images/santiago_normal_2.jpg",
    "media/geo_images/sevilla_normal_1.jpg",
    "media/geo_images/sevilla_normal_2.jpg",
    "media/geo_images/sevilla_normal_3.jpg",
    "media/geo_images/sevilla_normal_4.jpg",
    "media/geo_images/sheffield_normal_1.jpg",
    "media/geo_images/sheffield_normal_2.jpg",
    "media/geo_images/sheffield_normal_3.jpg",
    "media/geo_images/sheffield_normal_4.jpg",
    "media/geo_images/sidney_normal_1.jpg",
    "media/geo_images/sidney_normal_2.jpg",
    "media/geo_images/sidney_normal_3.jpg",
    "media/geo_images/sidney_normal_4.jpg",
    "media/geo_images/spain_normal_1.jpg",
    "media/geo_images/spain_normal_2.jpg",
    "media/geo_images/spain_normal_3.jpg",
    "media/geo_images/spain_normal_4.jpg",
    "media/geo_images/spain_normal_5.jpg",
    "media/geo_images/spain_normal_6.jpg",
    "media/geo_images/stockholm_normal_1.jpg",
    "media/geo_images/stockholm_normal_2.jpg",
    "media/geo_images/stockholm_normal_3.jpg",
    "media/geo_images/stockholm_normal_4.jpg",
    "media/geo_images/sweden_normal_1.jpg",
    "media/geo_images/sweden_normal_2.jpg",
    "media/geo_images/sweden_normal_3.jpg",
    "media/geo_images/sweden_normal_4.jpg",
    "media/geo_images/sweden_normal_5.jpg",
    "media/geo_images/sweden_normal_6.jpg",
    "media/geo_images/toulouse_normal_1.jpg",
    "media/geo_images/toulouse_normal_2.jpg",
    "media/geo_images/toulouse_normal_3.jpg",
    "media/geo_images/toulouse_normal_4.jpg",
    "media/geo_images/united_kingdom_normal_1.jpg",
    "media/geo_images/united_kingdom_normal_2.jpg",
    "media/geo_images/united_kingdom_normal_3.jpg",
    "media/geo_images/united_kingdom_normal_4.jpg",
    "media/geo_images/united_kingdom_normal_5.jpg",
    "media/geo_images/united_kingdom_normal_6.jpg",
    "media/geo_images/uppsala_normal_1.jpg",
    "media/geo_images/uppsala_normal_2.jpg",
    "media/geo_images/uppsala_normal_3.jpg",
    "media/geo_images/uppsala_normal_4.jpg",
    "media/geo_images/usa_normal_1.jpg",
    "media/geo_images/usa_normal_2.jpg",
    "media/geo_images/usa_normal_3.jpg",
    "media/geo_images/usa_normal_4.jpg",
    "media/geo_images/valparaiso_normal_1.jpg",
    "media/geo_images/valparaiso_normal_2.jpg",
    "media/geo_images/washington_normal_1.jpg",
    "media/geo_images/washington_normal_2.jpg",
    "media/geo_images/york_normal_1.jpg",
    "media/geo_images/york_normal_2.jpg", ]; // Vi gör en variabel som håller i våra bilder.
  
    for (let i = 0; i < 3; i++) { //Sedan skapar jag en for-loop som loppar 3 gånger. 
    let randomIndex = Math.floor(Math.random() * imagePaths.length); // En random index skapas.
    let img = document.createElement('img'); // Vi skapar vårt img objekt med hjälp av DOM 
    img.src = imagePaths[randomIndex]; // img.src är DOM, vi säger att det värdet som vårt DOM ska ha är vår sök väg, random index har värdet en random sök väg enligt ovan kod. 
    container.appendChild(img); //Vi lägger till alla bilder till förälder elementet vilket är container. Container är positionen som vi gett i structure.js
  }
  

  
  let headerTextContainer = document.createElement("div"); //Här skapar vi vår HTML objekt med DOM
  let headerText = document.createElement('h1');
  let headerText2 = document.createElement('h1');
  headerText.textContent = "Utbytesstudier"; //Här säger vi vad text innehållet ska innehålla.
  headerText2.textContent = "Missa inte chansen!";
  
  container.appendChild(headerTextContainer); //Lägger till texten till vår header 
  headerTextContainer.appendChild(headerText); // Lägger till texten i vår textcontainer
  headerTextContainer.appendChild(headerText2); //Lägger till texten i vår textcontainer
  
  headerTextContainer.className = "header_text"; //Ger vår text container 

}

